### ISSUE TITLE
Cell method doesn't sum to 1 per column

### ISSUE THREAD

**Issue by ajandria** [caanene1/Decosus#11]
Hi,

Thank you for developing this tool.

I have a question regarding the overall results. As I understand the 'Sample' method returns a data frame with the given cell signatures for each sample (similar to xCell). However, the 'Cell' method should return the cell fractions for each sample if I have read correctly. Surprisingly, after retrieving the 'main_cells' data.frame object by running 'cosDeco' function, the sum of rows per columns is not equal or close to 1. 

Could you please correct me if my understanding is wrong and how to properly interpret the results. 

Many thanks

**Comment by caanene1** [comment]
Hi Ajandria,
Thanks for your feedback. 
The main_cell out is different from the main_sample out. Because it compares cells, scaling to 1 is not meaningful.
 So the results you are getting are correct.
